### ISSUE TITLE
Crack open a cold one to celebrate 1 year of being done with capping

### ISSUE THREAD

**Issue by brendon-boldt** [brendon-boldt/imago-imaginis#71]
December 6th marks having been done with capping for a whole year. Crack open a cold one or enjoy yourself however to celebrate.

**Comment by exzackly** [comment]
![img_0415](https://user-images.githubusercontent.com/9475193/49628312-515a0780-f998-11e8-9b3d-1494989c7aa9.jpg)
Feature implemented
